### ISSUE TITLE
Rough translation of 鹘鹰反赌平台 (0/f7205881-3904-42ec-ab2c-04f36fa24785.md)

### ISSUE THREAD

**Issue by subsys-R9boq8** [mttaggart/I-S00N#3]
I roughly translated the product description of [鹘鹰反赌平台](https://github.com/mttaggart/I-S00N/blob/main/0/f7205881-3904-42ec-ab2c-04f36fa24785.md) to English. However since I don't know how to use git or how do you want it to be represented, I write it to a text file and zipped it:
  
[鹘鹰反赌平台.zip](https://github.com/mttaggart/I-S00N/files/14394955/falcon.anti-gambling.platform.zip)

**Comment by subsys-R9boq8** [comment]
This translation came with license [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en).

**Comment by jj551** [comment]
> [我粗略地将鹘鹰反赌平台](https://github.com/mttaggart/I-S00N/blob/main/0/f7205881-3904-42ec-ab2c-04f36fa24785.md)的产品描述翻译成了英文。然而，由于我不知道如何使用 git 或你希望如何表示它，所以我将其写入一个文本文件并压缩：
> 
> [鹘鹰反赌平台.zip](https://github.com/mttaggart/I-S00N/files/14394955/falcon.anti-gambling.platform.zip)

如果你是名优秀的红队请留下联系方式

**Comment by mttaggart** [comment]
Hi, @subsys-R9boq8! I appreciate this effort, but in this state, the translation represents a great deal of additional work for me. If you could please use the filename conventions that have been established, I'd really appreciate it. See [this section](https://github.com/mttaggart/I-S00N/blob/main/0/12756724-394c-4576-b373-7c53f1abbd94-en.md) for examples. Note that the translated PNGs end in `.en.png`, but maintain the original filename.

**Comment by subsys-R9boq8** [comment]
> If you could please use the filename conventions that have been established, I'd really appreciate it.

Sure thing!

> Note that the translated PNGs end in `.en.png`, but maintain the original filename.

@mttaggart Some pages have more than two pictures, how should I name them? Would "UUID"_"original page number"_"number of pic in the page".en.png be good?

**Comment by subsys-R9boq8** [comment]
The version with updated naming contention is here:
[FAGP.zip](https://github.com/mttaggart/I-S00N/files/14403378/FAGP.zip)

I don't really understand Markdown so something in the markdown file may not have the expected effects, please take extra care.

**Comment by Mystra007** [comment]
I understood most of it by using the yandex image translator . That could do a good initial version of a translation in my opinion. Would also be nice to have pdfs instead of impossible to copy-paste pictures

**Comment by subsys-R9boq8** [comment]
> Would also be nice to have pdfs instead of impossible to copy-paste pictures

I hope so but the original leaked content is just these png pictures (of every page of documents, I guess?) which is impossible to copy-paste. But I can create a PDF file from the translated pictures and text.

Do you need such a PDF version? @mttaggart

**Comment by mttaggart** [comment]
I really don't see the need for a less parseable data format. The images are here primarily because of the diagrams and tables, which the OCR translations struggled with, and for clarity. I'm more than happy to accept PRs of a) better translations for the images, and b) better text translations for the text.

**Comment by mttaggart** [comment]
@subsys-R9boq8 your translations have been included in a98adc3a962e69ea2b74fab1bfc993aa9a2af30b. Thank you!
